swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger Petstore
  description: >
    A sample API that uses a petstore as an example
    to demonstrate features in the swagger-2.0 specification
consumes:
  - application/json
produces:
  - application/json
basePath: /api
paths:
  /test:
    get:
      description: 'Index'
      x-cache:
          expire: 10000
      x-controller:
        - file: user
          handler: isLogin
        - file: page
          handler: userPage
      parameters:
        - name: id
          in: query
          description: id
          type: string
          required: true
        - name: who
          in: query
          description: who visit the index
          required: true
          type: string

      responses:
        '200':
          description: Index response
          schema:
            type: string
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'

definitions:
  errorModel:
    title: Error Model
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      helpURL:
        type: string
        format: url
